### ISSUE TITLE
关于改进问题

### ISSUE THREAD

**Issue by QingChengLineOne** [iLGZH-y/Generative-Face-Inpainting-with-Landmark#1]
能详细介绍一下您的改进内容吗

**Comment by mq-yuan** [comment]
在人脸重建过程中，引入了人脸关键点约束。人脸具有高度的结构性信息，是区分不同人的关键因素。因此，可以利用人脸关键点信息对重建结果进行上层信息约束，以提高生成人脸的结构完整性。

具体来说，使用Insightface分别对原始图像和重建图像提取关键点，并计算两个关键点向量的L1损失。
```python
def Discriminator_Network_Loss(real_img, fake_img, det_size):
    real_landmark = get_landmark(real_img, det_size=det_size).to(device)
    fake_landmark = get_landmark(fake_img, det_size=det_size).to(device)
    return F.l1_loss(real_landmark, fake_landmark)
    
    
loss_landmark = Discriminator_Network_Loss(real_img, fake_img, input_generator_size)
loss = loss_real + loss_fake + loss_landmark
```

**Comment by QingChengLineOne** [comment]
> 在人脸重建过程中，引入了人脸关键点约束。人脸具有高度的结构性信息，是区分不同人的关键因素。因此，可以利用人脸关键点信息对重建结果进行上层信息约束，以提高生成人脸的结构完整性。
> 
> 具体来说，使用Insightface分别对原始图像和重建图像提取关键点，并计算两个关键点向量的L1损失。
> 
> ```python
> def Discriminator_Network_Loss(real_img, fake_img, det_size):
>     real_landmark = get_landmark(real_img, det_size=det_size).to(device)
>     fake_landmark = get_landmark(fake_img, det_size=det_size).to(device)
>     return F.l1_loss(real_landmark, fake_landmark)
>     
>     
> loss_landmark = Discriminator_Network_Loss(real_img, fake_img, input_generator_size)
> loss = loss_real + loss_fake + loss_landmark
> ```
好的，谢谢
